"""init

Revision ID: b9b0dab72c78
Revises: 
Create Date: 2026-08-18 08:35:36.788267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b0dab72c78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_fts'), table_name='items', postgresql_using='gin')
    op.create_index('ix_items_fts', 'items', [sa.literal_column("to_tsvector('simple', coalesce(title,'') || ' ' || coalesce(summary_one,''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_fts', table_name='items', postgresql_using='gin')
    op.create_index(op.f('ix_items_fts'), 'items', [sa.literal_column("to_tsvector('simple'::regconfig, (COALESCE(title, ''::text) || ' '::text) || COALESCE(summary_one, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
